### ISSUE TITLE
can set LD_LIBRARY_PATH in the source code, not use command line outside?

### ISSUE THREAD

**Issue by gongluck** [gershnik/android-cmdline-jni#1]
i had tried add code
```c++
setenv("LD_LIBRARY_PATH", "/apex/com.android.art/lib:/apex/com.android.runtime/lib", 1);
```
before call dlopen, but it not work.
Looking forward to your reply, thank you.

**Comment by gershnik** [comment]
No, this won't work. It isn't an Android thing too but standard Linux behavior. By the time your code in `main()` runs and modifies `LD_LIBRARY_PATH`  the dynamic loader has long been initialized and used the environment the process was started with. The _only_ way to set `LD_LIBRARY_PATH` is to set it before the process launches.

If you really, really want to do it from inside the only way I can think about is to set it and then `fork`/`exec` yourself again.

Out of curiosity, why setting it from command line doesn't work for you?

**Comment by gongluck** [comment]
> No, this won't work. It isn't an Android thing too but standard Linux behavior. By the time your code in `main()` runs and modifies `LD_LIBRARY_PATH`  the dynamic loader has long been initialized and used the environment the process was started with. The _only_ way to set `LD_LIBRARY_PATH` is to set it before the process launches.
> 
> 
> 
> If you really, really want to do it from inside the only way I can think about is to set it and then `fork`/`exec` yourself again.
> 
> 
> 
> Out of curiosity, why setting it from command line doesn't work for you? 

Thanks for your reply. Your answer gave me some ideas. 
I want to hide all the details as much as possible, at least the implementation of the program will not be obvious, so I don't want to set the environment variables in the command line. 
The method of using fork/exec is great!
